language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
before_script:
  - "sudo gem update --system 1.6.2"
  - "cp config/database.yml.travis config/database.yml"
  - "cp config/webistrano.yml.sample config/webistrano.yml"
script: "bundle exec rake db:create db:migrate test:units test:functionals test:non_transactional"
